# Question 1:

In [1]:

# The most comments have removed from the notebook, ann.ipynb, given in Lab 6, for simplicity.


# ann.ipynb

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# pip install tensorflow

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [3]:

# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Using TensorFlow backend.


Epoch 1/100
8000/8000 [==============================] - 1s 155us/step - loss: 0.4809 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 122us/step - loss: 0.4280 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4230 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.4195 - acc: 0.8184
Epoch 5/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.4167 - acc: 0.8244
Epoch 6/100
8000/8000 [==============================] - 1s 131us/step - loss: 0.4150 - acc: 0.8300
Epoch 7/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.4132 - acc: 0.8300
Epoch 8/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.4118 - acc: 0.8326
Epoch 9/100
8000/8000 [==============================] - 1s 121us/step - loss: 0.4109 - acc: 0.8332
Epoch 10/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4096 - acc: 0.8337

You will add codes to the following cell for making prediction

In [33]:
dic = {"Geography": ["France"],
            "Credit Score": [600],
            "Gender": ["Male"],
            "Age": [40],
            "Tenure": [3],
            "Balance": [60000],
            "Number of Products": [2],
            "HasCrCard": [1],
            "IsActiveMember": [1],
            "Estimated Salary": [50000]}
x_ask = pd.DataFrame(dic).values

In [37]:
dataset.head(2)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   

   Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2      0.00              1          1               1   
1       1  83807.86              1          0               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0

In [36]:
X[:2]

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, 0.0000000e+00,
        4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, 0.0000000e+00,
        4.1000000e+01, 1.0000000e+00, 8.3807860e+04, 1.0000000e+00,
        0.0000000e+00, 1.0000000e+00, 1.1254258e+05]])

In [48]:
x_ask=np.array([np.array([0.0,0.0,600.0,1.0,
      40,3,60000,2,
      1,1,50000])])

In [49]:
x_ask.shape

(1, 11)

In [50]:
# Part 3 - Making predictions and evaluating the model

# Here is the place, where you add the codes for question given at beginning.

y_pred = classifier.predict(X_test)
y_pred = y_pred>0.5
new_prediction = classifier.predict(x_ask)

# Making the Confusion Matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


In [51]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [52]:
cm

array([[1549,   46],
       [ 274,  131]], dtype=int64)

In [53]:
new_prediction

array([[0.]], dtype=float32)